### ISSUE TITLE
if the sheet contains a scrollview, you can't scroll

### ISSUE THREAD

**Issue by softlion** [the49ltd/The49.Maui.BottomSheet#27]
Is that an unsupported scenario ?
If it has a handle, the top part with the handle should be where it captures the swipe ? And let the scrolling part scroll down ?

**Comment by paulvarache** [comment]
Hi,

I have been able to do what you describe, but there is one catch. At the moment, BottomSheets size themselves to the hight of the window, meaning if your sheet doesn't have a Fullscreen detent and the ScrollView content is smaller than the height of the window, the ScrollView won't scroll.

As a workaround, restrict the height of your ScrollView to something smaller than the height of the opened BottomSheet, I know this is not ideal but it should allow you to scroll. The other option is to have a FullScreen detent. This will make the scroll gesture first expand the sheet, then once fully opened, the ScrollView will scroll.

Before 1.0.0 I plan to have the BottomSheet calculate their height based on the biggest Detent, instead of the full size of the window, which should fix this issue.

I'll keep this issue open to track the fix I need to implement

**Comment by paulvarache** [comment]
In the latest version, bottom sheets now size themselves based on their tallest detents, this should solve this issue
