### ISSUE TITLE
Is there an easy was to disable the rounded corners or provide a bool Property for this?

### ISSUE THREAD

**Issue by dg2k** [the49ltd/The49.Maui.BottomSheet#48]
I prefer the square corners than rounded corners for Android. I followed the customization with a theme.xml as suggested, which works when the window is expanded but not for minimal window such as a small HeightDetent.

I recall that the early versions had square corners, so I would assume getting to that programmatically should be easy. Perhaps making this an option with bool property IsRoundedCorners would be great.

Can this be accommodated?

Thank you.

**Comment by paulvarache** [comment]
I'd love to have that in, it makes sense. It is not supported for now since it is fairly difficult to do it on Android. It would require override the background drawable with a custom one, but that would also remove a bunch of default Material design styles

I'll keep this open as I may find a way around that at some point.

I am surprised the themes modifications didn't remove the corner radius, in theory setting a 0dp radius would remove the corner radius on all states

**Comment by paulvarache** [comment]
Material 3 Bottom sheets can be themed as shown here: https://github.com/material-components/material-components-android/blob/master/docs/components/BottomSheet.md#theming-bottom-sheets

So in theory the styles provided should work, but for some reason it doesn't seem to work. I have looked at it a little bit but will need more time to figure out which styles need to be set for Android to pick that up

**Comment by paulvarache** [comment]
I finally got around to do this and there is now a `CornerRadius` property you can set to 0 for a square sheet or any other value you like. Works for both Android and iOS

**Comment by dg2k** [comment]
Thank you very much indeed.
I will check it out soon.
