### ISSUE TITLE
Use handle to set height

### ISSUE THREAD

**Issue by OudomMunint** [the49ltd/The49.Maui.BottomSheet#58]
Is it possible to use the handle to dynamically set the height of the bottom sheet?

**Comment by paulvarache** [comment]
This behaviour is not supported by either the Android BottomSheet or iOS SheetPresentationController. The goal of this package is to expose those 2 features as one in MAUI, so I will consider this out of scope.

For a cross platform solution to this issue, it seems to me like the best option is to make one using MAUI controls, instead of using native views
